In [1]:
print("Hello Jupyter")

Hello Jupyter


In [1]:
import numpy as np
mylist = [1,2,3]
type(mylist)

list

In [2]:
np.array((mylist))

array([1, 2, 3])

In [4]:
#we can also write matrix. Very basic up to now.
my_matrix=[[1,2,3],[2,4,0],[10,2,1]]
np.array(my_matrix)

array([[ 1,  2,  3],
       [ 2,  4,  0],
       [10,  2,  1]])

In [11]:
#We can also create a range in an array, the same way as range for lists
print(list(range(0,20,4)))
#But now for arrays in numpy
np.arange(0,10,2)

[0, 4, 8, 12, 16]


array([0, 2, 4, 6, 8])

In [16]:
#We can also define zeros to fill an array
np.zeros(4)
#the same for matrices:
np.zeros((2,5))
#and the same also for number of ones!
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [83]:
#Other important function is linspace
#Get evenly spaces from first value, to third value, an the number of elements
#np.linspace(start,end-included,number of elements)
#Examples
np.linspace(0,10,3)
np.linspace(0,20,11)
myarray=np.array(np.linspace(0,10,101))
print(myarray)

[ 0.   0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1.   1.1  1.2  1.3
  1.4  1.5  1.6  1.7  1.8  1.9  2.   2.1  2.2  2.3  2.4  2.5  2.6  2.7
  2.8  2.9  3.   3.1  3.2  3.3  3.4  3.5  3.6  3.7  3.8  3.9  4.   4.1
  4.2  4.3  4.4  4.5  4.6  4.7  4.8  4.9  5.   5.1  5.2  5.3  5.4  5.5
  5.6  5.7  5.8  5.9  6.   6.1  6.2  6.3  6.4  6.5  6.6  6.7  6.8  6.9
  7.   7.1  7.2  7.3  7.4  7.5  7.6  7.7  7.8  7.9  8.   8.1  8.2  8.3
  8.4  8.5  8.6  8.7  8.8  8.9  9.   9.1  9.2  9.3  9.4  9.5  9.6  9.7
  9.8  9.9 10. ]


In [22]:
#Identity matrix-very important for linear algebra-squared matrix (n x n) order
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [66]:
#Now lets create random distributions of data. huuuh
#First simple one:
#Return random numbers in a table. Can also return according to probability distributions.
#This simplify a lot and can help in the creation of particles in solar system. 
print(np.random.rand(2,3))
#One example for a normal distribution:
print(np.random.randn(10))
#Simple ones, to generate ints:
#follows the rule:
#random.randint(low, high=None, size=None, dtype=int)-> does not include the high number
print(np.random.randint(0,11,20))
print(np.random.randint(4,size=20))
print(np.random.randint(0,10,size=(2,4)))
#We can also use np.random.seed(42)-generate a seed set of values. 
#The number is arbitrary and generate the same numbers
print("check it out")
print(np.random.seed(42))
print(np.random.rand(3))

[[0.15601864 0.15599452 0.05808361]
 [0.86617615 0.60111501 0.70807258]]
[-0.46947439  0.54256004 -0.46341769 -0.46572975  0.24196227 -1.91328024
 -1.72491783 -0.56228753 -1.01283112  0.31424733]
[2 6 3 8 2 4 2 6 4 8 6 1 3 8 1 9 8 9 4 1]
[3 3 2 3 2 3 0 3 2 2 1 0 3 1 3 3 1 1 1 1]
[[9 3 5 1]
 [9 1 9 3]]
check it out
None
[0.37454012 0.95071431 0.73199394]


In [48]:
#We can also reshape the array, in other format/order
arr = np.arange(0,25)
print(arr)
arr.reshape(5,5)
#


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [78]:
#We can also find the max and min valyes of an array. Easy peasy
np.random.seed(42)
arrayx = np.random.rand(2,4)
print(arrayx)
print(arrayx.reshape((4,2)))
#Other basic important functions:
print(arrayx.min())
print(arrayx.max())
print(arrayx.argmin())
print(arrayx.argmax())
arrayx.dtype

[[0.37454012 0.95071431 0.73199394 0.59865848]
 [0.15601864 0.15599452 0.05808361 0.86617615]]
[[0.37454012 0.95071431]
 [0.73199394 0.59865848]
 [0.15601864 0.15599452]
 [0.05808361 0.86617615]]
0.05808361216819946
0.9507143064099162
6
1


dtype('float64')

In [79]:
#array.shape() also tells us the shape of our array
arrayx.shape

(2, 4)

In [88]:
#INDEXES,SELECTIONS, GRABBING, SLICES
new_array = np.arange(0,11)
new_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [105]:
new_array[8]
arr[1:5]
arr[0:5]
arr[:5]
arr[:5]=100

In [116]:
array_original=np.arange(0,11)
array_original
array_imitation = array_original[0:5]
array_imitation
array_imitation[0:3]=100
array_imitation
array_original
#Space in memory is the same. If we make two arrays equal, they will refer to the same memory.
#In the case that we do not want the values to be altered, we need to copy the array by:
array_mimic =  array_original.copy()
array_mimic
array_mimic[4:10]=20
array_mimic
array_original

array([100, 100, 100,   3,   4,   5,   6,   7,   8,   9,  10])

In [125]:
#In the case of a 2d array.
array_1d = np.arange(5,50,5)
array_2d= array_1d.reshape((3,3))
print(array_2d)
array_2d.shape
#we can get specific terms of the array.Examples:
array_2d[1,1]
array_2d[:2,1:]
#we can get subsets of the matrix. Wow. Very nice. :)
#array_2d = np.array([5,10,15],[])

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


array([[10, 15],
       [25, 30]])

In [126]:
#Lets now use comparisons and see the kind of stuff we can do:
array_1d>5

array([False,  True,  True,  True,  True,  True,  True,  True,  True])

In [129]:
#So we can not write a boolean array!
bool_array = array_1d>5
#and make an array out of it!
array_1d[bool_array]
#The simplest way to do is:
array_1d[array_1d>5]

array([10, 15, 20, 25, 30, 35, 40, 45])

In [136]:
import numpy as np
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])
total_rolls_over_two = np.count_nonzero(dice_rolls>2)
print(total_rolls_over_two)
total_rolls_over_two = len(dice_rolls[dice_rolls>2])
total_rolls_over_two

19


19

In [146]:
#Arrays Operations
array1=np.linspace(0,12,7)
array1+array1
#sum the elements one by one. The same with the other elemtns
array1.dtype

dtype('float64')